#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

xrandr -s 1920x1080
xrandr --dpi 96

#set_wallpaper.sh &
lxpanel &
tint2 &
#gxkb &

# start openbox
exec openbox
