#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

xrandr --dpi 96 &
xrandr -s 1920x1200 &

set_wallpaper.sh &
lxpanel &
tint2 &
gxkb &

#exec lxpanel &

# start openbox
exec openbox
